- name: Web App Wipe
  tags: [wipe]
  block:
    - name: Remove app container
      community.docker.docker_compose_v2:
        project_src: "{{ web_app_path }}"
        state: absent
        remove_orphans: true
        remove_images: all
        remove_volumes: true

    - name: Remove directory
      ansible.builtin.file:
        path: "{{ web_app_path }}"
        state: absent