---
- name: Update apt
  ansible.builtin.apt:
    update_cache: true

- name: Add Docker's GPG key
  ansible.builtin.apt_key:
    url: "{{ docker_gpg_apt_key_url }}"
    state: present

- name: Add Docker Repo
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
    state: present