- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: true
  
- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker

- name: Install Docker
  import_tasks: install_docker.yml

- name: Install docker-compose
  import_tasks: install_compose.yml

