---
- name: Install PIP
  ansible.builtin.include_tasks:
    file: install_pip.yml
- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    
- name: Install Docker
  ansible.builtin.include_tasks:
    file: install_docker.yml

- name: Install Docker Compose
  ansible.builtin.include_tasks:
    file: install_compose.yml