name: Node.js CI

on:
  push:
    paths:
      - 'app_js/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('app_js/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' 

      - name: Install dependencies
        run: |
          npm install
        working-directory: app_js

      - name: Lint code
        run: |
          npm run lint 
        working-directory: app_js

      - name: Run tests
        run: |
          npm run test
        working-directory: app_js


  security:
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        with:
          args: --skip-unresolved app_js/
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker:
    runs-on: ubuntu-latest

    needs:
      - build
      - security
    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build  Docker image
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/app_js:latest ./app_js

      - name: Push Docker image
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/app_js:latest